apiVersion: v1
entries:
  jetic-ingress:
  - apiVersion: v2
    appVersion: "1.4"
    created: "2024-03-13T14:02:48.224032-05:00"
    description: A Helm chart for configuring your jetic-ingress rules
    digest: f47f7cc87f6e3a45471b8bcfaef8546a1e3d48725610486306826993e0edcaa5
    icon: https://app.jetic.io/favicon.ico
    name: jetic-ingress
    type: application
    urls:
    - https://helm.jetic.io/jetic-ingress/charts/jetic-ingress-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: "1.4"
    created: "2024-03-13T14:02:48.223411-05:00"
    description: A Helm chart for configuring your jetic-ingress rules
    digest: 25f505dbe27f9874c00105a5fbfa70fbbaae48dc178ac333769e39b3dc11e16c
    icon: https://app.jetic.io/favicon.ico
    name: jetic-ingress
    type: application
    urls:
    - https://helm.jetic.io/jetic-ingress/charts/jetic-ingress-1.0.0.tgz
    version: 1.0.0
generated: "2024-03-13T14:02:48.222852-05:00"
